In [2]:
import numpy as np
from math import sqrt

In [3]:
# Set up the basic matrices
print("Reversible quantum gates")
print("------------------------------")

qubits = {
    "|0\u232a": np.array([1, 0]),
    "|1\u232a": np.array([0, 1]),
    "(|0\u232a+|1\u232a)/\u221a2": 1 / sqrt(2) * np.array([1, 1]),
}

for q in qubits:
    print(q, "\n", qubits[q])
print("\n")

Reversible quantum gates
------------------------------
|0〉 
 [1 0]
|1〉 
 [0 1]
(|0〉+|1〉)/√2 
 [0.70710678 0.70710678]




In [4]:
print("Matrix representations of our gates:")
print("-------------------------------------")
gates = {
    "id": np.array([[1, 0], [0, 1]]),
    "x": np.array([[0, 1], [1, 0]]),
    "y": np.array([[0, -1.0j], [1.0j, 0]]),
    "z": np.array([[1, 0], [0, -1]]),
    "h": 1 / sqrt(2) * np.array([[1, 1], [1, -1]]),
    "s": np.array([[1, 0], [0, 1j]]),
}
diff = ""
for g in gates:
    print("\n", g, "\n", gates[g].round(3))
    if gates[g].all == np.matrix.conjugate(gates[g]).all:
        diff = g + " (Same as original)"
    else:
        diff = g + "\u2020 (Complex numbers conjugated)"

    print("Reversed", g, "=", diff, "\n", np.matrix.conjugate(gates[g]).round(3))

print("\n")


Matrix representations of our gates:
-------------------------------------

 id 
 [[1 0]
 [0 1]]
Reversed id = id (Same as original) 
 [[1 0]
 [0 1]]

 x 
 [[0 1]
 [1 0]]
Reversed x = x (Same as original) 
 [[0 1]
 [1 0]]

 y 
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
Reversed y = y† (Complex numbers conjugated) 
 [[ 0.-0.j -0.+1.j]
 [ 0.-1.j  0.-0.j]]

 z 
 [[ 1  0]
 [ 0 -1]]
Reversed z = z (Same as original) 
 [[ 1  0]
 [ 0 -1]]

 h 
 [[ 0.707  0.707]
 [ 0.707 -0.707]]
Reversed h = h (Same as original) 
 [[ 0.707  0.707]
 [ 0.707 -0.707]]

 s 
 [[1.+0.j 0.+0.j]
 [0.+0.j 0.+1.j]]
Reversed s = s† (Complex numbers conjugated) 
 [[1.-0.j 0.-0.j]
 [0.-0.j 0.-1.j]]




In [5]:
# Demonstrate that the basic quantum gates are reversible
# by applying the gate then its’ complex conjugate,
# and then comparing the outcome with the input.

for g in gates:
    input("Press enter...")
    print("Gate:", g)
    print("-------")
    for q in qubits:
        print("\nOriginal qubit: ", q, "\n", qubits[q].round(3))
        print("Qubit after", g, "gate: \n", np.dot(gates[g], qubits[q]).round(3))
        print(
            "Qubit after reversed",
            g,
            "gate.",
            "\n",
            np.dot(np.dot(gates[g], qubits[q]), np.matrix.conjugate(gates[g])).round(3),
        )
    print("\n")


Press enter... 


Gate: id
-------

Original qubit:  |0〉 
 [1 0]
Qubit after id gate: 
 [1 0]
Qubit after reversed id gate. 
 [1 0]

Original qubit:  |1〉 
 [0 1]
Qubit after id gate: 
 [0 1]
Qubit after reversed id gate. 
 [0 1]

Original qubit:  (|0〉+|1〉)/√2 
 [0.707 0.707]
Qubit after id gate: 
 [0.707 0.707]
Qubit after reversed id gate. 
 [0.707 0.707]




Press enter... 


Gate: x
-------

Original qubit:  |0〉 
 [1 0]
Qubit after x gate: 
 [0 1]
Qubit after reversed x gate. 
 [1 0]

Original qubit:  |1〉 
 [0 1]
Qubit after x gate: 
 [1 0]
Qubit after reversed x gate. 
 [0 1]

Original qubit:  (|0〉+|1〉)/√2 
 [0.707 0.707]
Qubit after x gate: 
 [0.707 0.707]
Qubit after reversed x gate. 
 [0.707 0.707]




Press enter... 


Gate: y
-------

Original qubit:  |0〉 
 [1 0]
Qubit after y gate: 
 [0.+0.j 0.+1.j]
Qubit after reversed y gate. 
 [1.+0.j 0.+0.j]

Original qubit:  |1〉 
 [0 1]
Qubit after y gate: 
 [0.-1.j 0.+0.j]
Qubit after reversed y gate. 
 [0.+0.j 1.+0.j]

Original qubit:  (|0〉+|1〉)/√2 
 [0.707 0.707]
Qubit after y gate: 
 [0.-0.707j 0.+0.707j]
Qubit after reversed y gate. 
 [0.707+0.j 0.707+0.j]




Press enter... 


Gate: z
-------

Original qubit:  |0〉 
 [1 0]
Qubit after z gate: 
 [1 0]
Qubit after reversed z gate. 
 [1 0]

Original qubit:  |1〉 
 [0 1]
Qubit after z gate: 
 [ 0 -1]
Qubit after reversed z gate. 
 [0 1]

Original qubit:  (|0〉+|1〉)/√2 
 [0.707 0.707]
Qubit after z gate: 
 [ 0.707 -0.707]
Qubit after reversed z gate. 
 [0.707 0.707]




Press enter... 


Gate: h
-------

Original qubit:  |0〉 
 [1 0]
Qubit after h gate: 
 [0.707 0.707]
Qubit after reversed h gate. 
 [1. 0.]

Original qubit:  |1〉 
 [0 1]
Qubit after h gate: 
 [ 0.707 -0.707]
Qubit after reversed h gate. 
 [0. 1.]

Original qubit:  (|0〉+|1〉)/√2 
 [0.707 0.707]
Qubit after h gate: 
 [1. 0.]
Qubit after reversed h gate. 
 [0.707 0.707]




Press enter... 


Gate: s
-------

Original qubit:  |0〉 
 [1 0]
Qubit after s gate: 
 [1.+0.j 0.+0.j]
Qubit after reversed s gate. 
 [1.+0.j 0.+0.j]

Original qubit:  |1〉 
 [0 1]
Qubit after s gate: 
 [0.+0.j 0.+1.j]
Qubit after reversed s gate. 
 [0.+0.j 1.+0.j]

Original qubit:  (|0〉+|1〉)/√2 
 [0.707 0.707]
Qubit after s gate: 
 [0.707+0.j    0.   +0.707j]
Qubit after reversed s gate. 
 [0.707+0.j 0.707+0.j]


