In [1]:
# Let's start by importing all we need.
import numpy as np
from math import sqrt

In [2]:
# Set up the basic matrices
print("Vector representations of our qubits:")
print("-------------------------------------")

qubits = {
    "|0\u27e9": np.array([1, 0]),
    "|1\u27e9": np.array([0, 1]),
    "(|0\u27e9+|1\u27e9)/\u221a2": 1 / sqrt(2) * np.array([1, 1]),
}

for q in qubits:
    print(q, "\n", qubits[q].round(3))

Vector representations of our qubits:
-------------------------------------
|0⟩ 
 [1 0]
|1⟩ 
 [0 1]
(|0⟩+|1⟩)/√2 
 [0.707 0.707]


In [3]:
print("Matrix representations of our quantum gates:")
print("--------------------------------------------")
gates = {
    "id": np.array([[1, 0], [0, 1]]),
    "x": np.array([[0, 1], [1, 0]]),
    "h": 1 / sqrt(2) * np.array([[1, 1], [1, -1]]),
}

for g in gates:
    print(g, "\n", gates[g].round(3))


Matrix representations of our quantum gates:
--------------------------------------------
id 
 [[1 0]
 [0 1]]
x 
 [[0 1]
 [1 0]]
h 
 [[ 0.707  0.707]
 [ 0.707 -0.707]]


In [4]:
print("Gate manipulations of our qubits:")
print("---------------------------------")

for g in gates:
    print("Gate:", g)
    for q in qubits:
        print(q, "\n", qubits[q].round(3), "->", np.dot(gates[g], qubits[q]).round(3))
    print("\n")


Gate manipulations of our qubits:
---------------------------------
Gate: id
|0⟩ 
 [1 0] -> [1 0]
|1⟩ 
 [0 1] -> [0 1]
(|0⟩+|1⟩)/√2 
 [0.707 0.707] -> [0.707 0.707]


Gate: x
|0⟩ 
 [1 0] -> [0 1]
|1⟩ 
 [0 1] -> [1 0]
(|0⟩+|1⟩)/√2 
 [0.707 0.707] -> [0.707 0.707]


Gate: h
|0⟩ 
 [1 0] -> [0.707 0.707]
|1⟩ 
 [0 1] -> [ 0.707 -0.707]
(|0⟩+|1⟩)/√2 
 [0.707 0.707] -> [1. 0.]




In [5]:
print("Vector representations of our two qubits:")
print("-----------------------------------------")

twoqubits = {
    "|00\u27e9": np.array([1, 0, 0, 0]),
    "|01\u27e9": np.array([0, 1, 0, 0]),
    "|10\u27e9": np.array([0, 0, 1, 0]),
    "|11\u27e9": np.array([0, 0, 0, 1]),
    "|PH\u27e9": np.array([0.5, -0.5, 0.5, -0.5]),
}

for b in twoqubits:
    print(b, "\n", twoqubits[b])


Vector representations of our two qubits:
-----------------------------------------
|00⟩ 
 [1 0 0 0]
|01⟩ 
 [0 1 0 0]
|10⟩ 
 [0 0 1 0]
|11⟩ 
 [0 0 0 1]
|PH⟩ 
 [ 0.5 -0.5  0.5 -0.5]


In [6]:
print("Matrix representations of our quantum gates:")
print("--------------------------------------------")
twogates = {
    "cx": np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]]),
    "swap": np.array([[1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]]),
}

for g in twogates:
    print(g, "\n", twogates[g].round())



Matrix representations of our quantum gates:
--------------------------------------------
cx 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
swap 
 [[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]


In [7]:
print("Gate manipulations of our qubits:")
print("---------------------------------")

for g in twogates:
    print("Gate:", g)
    for b in twoqubits:
        print(b, "\n", twoqubits[b], "->", np.dot(twogates[g], twoqubits[b]))
    print("\n")


Gate manipulations of our qubits:
---------------------------------
Gate: cx
|00⟩ 
 [1 0 0 0] -> [1 0 0 0]
|01⟩ 
 [0 1 0 0] -> [0 1 0 0]
|10⟩ 
 [0 0 1 0] -> [0 0 0 1]
|11⟩ 
 [0 0 0 1] -> [0 0 1 0]
|PH⟩ 
 [ 0.5 -0.5  0.5 -0.5] -> [ 0.5 -0.5 -0.5  0.5]


Gate: swap
|00⟩ 
 [1 0 0 0] -> [1 0 0 0]
|01⟩ 
 [0 1 0 0] -> [0 0 1 0]
|10⟩ 
 [0 0 1 0] -> [0 1 0 0]
|11⟩ 
 [0 0 0 1] -> [0 0 0 1]
|PH⟩ 
 [ 0.5 -0.5  0.5 -0.5] -> [ 0.5  0.5 -0.5 -0.5]


